name: trump-truth-social-archive

on:
  workflow_dispatch:
  schedule:
    # - cron: '47 10-23 * * *'  # Runs every hour at :47 from 10 AM to 11 PM UTC (5 AM - 6 PM ET)
    # - cron: '47 0-3 * * *'    # Runs every hour at :47 from 12 AM to 3 AM UTC (7 PM - 11 PM ET)
    - cron: '47 */4 * * *'  # Runs every 4 hours at :47

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout repo

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: install python packages
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: |
          set -e
          python scrape.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SCRAPE_PROXY_KEY: ${{ secrets.SCRAPE_PROXY_KEY }}
      
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp data/ s3://stilesdata.com/trump-truth-social-archive/ --recursive
          
      - name: commit files
        run: |
          set -e
          git config --local user.email "mattstiles@gmail.com"
          git config --local user.name "Matt Stiles"
          git add -A
          git commit -m "bot fetched and updated data" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"

      - name: push changes
        run: |
          set -e  # Stop execution if a command fails
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}